### ISSUE TITLE
How to install it on an actual device?

### ISSUE THREAD

**Issue by ssmenissy** [remirobert/Naruto-shippuden-iOS#1]
I'm having trouble installing it on an actual device. Is it available to install? If so, how to do so please.

**Comment by remirobert** [comment]
You have to get Xcode, and a iOS developer licence. Then build it on your device. That's all.

**Comment by ssmenissy** [comment]
Ok. Sounds good. Thanks.

**Comment by remirobert** [comment]
Good luck. I hope you will get success.

**Comment by ssmenissy** [comment]
By the way, has anyone successfully installed it already? If so, any help doing so. I run on Windows, so yeah.

**Comment by remirobert** [comment]
On Windows, i will never get success to install anything on your phone, because you need Xcode (ONLY available on OSX). Sorry.
